logging:
 level:
  root: info
server:
 servlet:
  context-path: /coope.dev
 port: 8080
spring:
 datasource:
  coopedev:
   url: jdbc:postgresql://localhost:5432/coopedev
   username: francis
   password: admin123
   driver-class-name: org.postgresql.Driver
 jpa:
  coopedev:
   hibernate:
    ddl-auto: update
    naming:
     physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
   properties:
    hibernate:
     dialect: org.hibernate.dialect.PostgreSQLDialect
     format_sql: true
   database: postgresql
   database-platform: org.hibernate.dialect.PostgreSQLDialect

jasper:
  localization:
    i18n: es_PY
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
       expiration: 604800000 # 7 days